from cv1.shapes import Shape
from cv1.green_screen import green_screen_realtime
from cv1.invisibility_cloak1 import invisibility_cloak
from cv1.detect_by_color import detect_objects_by_color_upgraded
from cv1.detect_by_color_vid import detect_objects_by_color_real_time
